import sqlite3
import pandas as pd

# Path to the data file generated by the sacct command
data_file = 'cluster_usage_data.txt'

# Create a connection to the SQLite database (it will create the file if it doesn't exist)
conn = sqlite3.connect('cluster_usage.db')

# Define a SQL query to create a table
# Adjust the column types and names based on the actual data from sacct
create_table_query = '''
    CREATE TABLE IF NOT EXISTS cluster_usage (
        JobID TEXT,
        User TEXT,
        Account TEXT,
        Partition TEXT,
        State TEXT,
        AllocCPUS INTEGER,
        Elapsed TEXT,
        Start TEXT,
        End TEXT,
        NCPUS INTEGER,
        NNodes INTEGER,
        TotalCPU TEXT,
        UserCPU TEXT,
        SystemCPU TEXT,
        CPUTime TEXT
    )
'''
conn.execute(create_table_query)

# Read the data into a Pandas DataFrame
# The delimiter and column names should match the output format of your sacct command
data = pd.read_csv(data_file, delimiter='|')

# Insert the data into the database
data.to_sql('cluster_usage', conn, if_exists='append', index=False)

# Close the database connection
conn.close()

